"""Initial migration

Revision ID: 0497e8629e9c
Revises: e6efe729a7f1
Create Date: 2025-05-24 21:10:30.987104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0497e8629e9c'
down_revision: Union[str, None] = 'e6efe729a7f1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_user_id_key', 'task', type_='unique')
    op.drop_constraint('task_user_id_fkey', 'task', type_='foreignkey')
    op.create_foreign_key(None, 'task', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'task', type_='foreignkey')
    op.create_foreign_key('task_user_id_fkey', 'task', 'user', ['user_id'], ['id'])
    op.create_unique_constraint('task_user_id_key', 'task', ['user_id'])
    # ### end Alembic commands ###
