"""Initial migration

Revision ID: aa9d08491844
Revises: 0497e8629e9c
Create Date: 2025-05-25 22:16:00.323099

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "aa9d08491844"
down_revision: Union[str, None] = "0497e8629e9c"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "task", "user_id", existing_type=sa.INTEGER(), nullable=True
    )
    op.drop_constraint("task_user_id_fkey", "task", type_="foreignkey")
    op.create_foreign_key(
        None, "task", "user", ["user_id"], ["id"], ondelete="SET NULL"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "task", type_="foreignkey")
    op.create_foreign_key(
        "task_user_id_fkey",
        "task",
        "user",
        ["user_id"],
        ["id"],
        ondelete="CASCADE",
    )
    op.alter_column(
        "task", "user_id", existing_type=sa.INTEGER(), nullable=False
    )
    # ### end Alembic commands ###
