"""Initial migration

Revision ID: bf8272badf1e
Revises: 4e9fb22c0d5e
Create Date: 2025-04-14 15:33:41.167631

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf8272badf1e'
down_revision: Union[str, None] = '4e9fb22c0d5e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('task_admin_is_fkey', 'task', type_='foreignkey')
    op.drop_column('task', 'admin_is')
    op.drop_column('users', 'is_admin')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('is_admin', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.add_column('task', sa.Column('admin_is', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('task_admin_is_fkey', 'task', 'users', ['admin_is'], ['id'])
    # ### end Alembic commands ###
