"""Initial migration

Revision ID: e6efe729a7f1
Revises: ee5844265dbf
Create Date: 2025-04-22 11:28:34.001156

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e6efe729a7f1"
down_revision: Union[str, None] = "ee5844265dbf"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, "task", ["title"])
    op.create_unique_constraint(None, "user", ["email"])
    op.create_unique_constraint(None, "user", ["name"])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "user", type_="unique")
    op.drop_constraint(None, "task", type_="unique")
    # ### end Alembic commands ###
