"""Initial migration

Revision ID: ee5844265dbf
Revises: 2b02563bb590
Create Date: 2025-04-14 19:18:26.035488

"""

from typing import Sequence, Union

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ee5844265dbf"
down_revision: Union[str, None] = "2b02563bb590"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("user", "password")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "user",
        sa.Column("password", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
